export const vestingData = [
    {
        period: "TGE",
        month: 0,
        gameplayRewards: "500,000,000",
        communityIncentives: "250,000,000",
        developmentFund: "0",
        liquidity: "250,000,000",
        status: "Released",
    },
    {
        period: "TGE+6M",
        month: 6,
        gameplayRewards: "500,000,000",
        communityIncentives: "250,000,000",
        developmentFund: "0",
        liquidity: "250,000,000",
        status: "Released",
    },
    {
        period: "TGE+12M",
        month: 12,
        gameplayRewards: "500,000,000",
        communityIncentives: "250,000,000",
        developmentFund: "0",
        liquidity: "250,000,000",
        status: "Pending",
    },
    {
        period: "TGE+16M",
        month: 16,
        gameplayRewards: "0",
        communityIncentives: "0",
        developmentFund: "40,000,000",
        liquidity: "0",
        status: "Pending",
    },
    {
        period: "TGE+17M",
        month: 17,
        gameplayRewards: "0",
        communityIncentives: "0",
        developmentFund: "40,000,000",
        liquidity: "0",
        status: "Pending",
    },
    {
        period: "TGE+18M",
        month: 18,
        gameplayRewards: "500,000,000",
        communityIncentives: "0",
        developmentFund: "40,000,000",
        liquidity: "0",
        status: "Pending",
    },
    {
        period: "TGE+19M",
        month: 19,
        gameplayRewards: "0",
        communityIncentives: "0",
        developmentFund: "40,000,000",
        liquidity: "0",
        status: "Pending",
    },
    {
        period: "TGE+20M",
        month: 20,
        gameplayRewards: "0",
        communityIncentives: "0",
        developmentFund: "40,000,000",
        liquidity: "250,000,000",
        status: "Pending",
    },
    {
        period: "TGE+21M",
        month: 21,
        gameplayRewards: "0",
        communityIncentives: "0",
        developmentFund: "40,000,000",
        liquidity: "0",
        status: "Pending",
    },
    {
        period: "TGE+22M",
        month: 22,
        gameplayRewards: "0",
        communityIncentives: "0",
        developmentFund: "40,000,000",
        liquidity: "0",
        status: "Pending",
    },
    {
        period: "TGE+23M",
        month: 23,
        gameplayRewards: "0",
        communityIncentives: "0",
        developmentFund: "40,000,000",
        liquidity: "0",
        status: "Pending",
    },
    {
        period: "TGE+24M",
        month: 24,
        gameplayRewards: "500,000,000",
        communityIncentives: "250,000,000",
        developmentFund: "40,000,000",
        liquidity: "0",
        status: "Pending",
    },
    {
        period: "TGE+25M",
        month: 25,
        gameplayRewards: "0",
        communityIncentives: "0",
        developmentFund: "40,000,000",
        liquidity: "0",
        status: "Pending",
    },
    {
        period: "TGE+26M",
        month: 26,
        gameplayRewards: "0",
        communityIncentives: "0",
        developmentFund: "40,000,000",
        liquidity: "0",
        status: "Pending",
    },
    {
        period: "TGE+27M",
        month: 27,
        gameplayRewards: "0",
        communityIncentives: "0",
        developmentFund: "40,000,000",
        liquidity: "0",
        status: "Pending",
    },
    {
        period: "TGE+28M",
        month: 28,
        gameplayRewards: "0",
        communityIncentives: "0",
        developmentFund: "40,000,000",
        liquidity: "0",
        status: "Pending",
    },
    {
        period: "TGE+29M",
        month: 29,
        gameplayRewards: "0",
        communityIncentives: "0",
        developmentFund: "40,000,000",
        liquidity: "0",
        status: "Pending",
    },
    {
        period: "TGE+30M",
        month: 30,
        gameplayRewards: "500,000,000",
        communityIncentives: "0",
        developmentFund: "40,000,000",
        liquidity: "0",
        status: "Pending",
    },
    {
        period: "TGE+31M",
        month: 31,
        gameplayRewards: "0",
        communityIncentives: "0",
        developmentFund: "40,000,000",
        liquidity: "0",
        status: "Pending",
    },
    {
        period: "TGE+32M",
        month: 32,
        gameplayRewards: "0",
        communityIncentives: "0",
        developmentFund: "40,000,000",
        liquidity: "0",
        status: "Pending",
    },
    {
        period: "TGE+33M",
        month: 33,
        gameplayRewards: "0",
        communityIncentives: "0",
        developmentFund: "40,000,000",
        liquidity: "0",
        status: "Pending",
    },
    {
        period: "TGE+34M",
        month: 34,
        gameplayRewards: "0",
        communityIncentives: "0",
        developmentFund: "40,000,000",
        liquidity: "0",
        status: "Pending",
    },
    {
        period: "TGE+35M",
        month: 35,
        gameplayRewards: "0",
        communityIncentives: "0",
        developmentFund: "40,000,000",
        liquidity: "0",
        status: "Pending",
    },
    {
        period: "TGE+36M",
        month: 36,
        gameplayRewards: "500,000,000",
        communityIncentives: "250,000,000",
        developmentFund: "40,000,000",
        liquidity: "0",
        status: "Pending",
    },
    {
        period: "TGE+37M",
        month: 37,
        gameplayRewards: "0",
        communityIncentives: "0",
        developmentFund: "40,000,000",
        liquidity: "0",
        status: "Pending",
    },
    {
        period: "TGE+38M",
        month: 38,
        gameplayRewards: "0",
        communityIncentives: "0",
        developmentFund: "40,000,000",
        liquidity: "0",
        status: "Pending",
    },
    {
        period: "TGE+39M",
        month: 39,
        gameplayRewards: "500,000,000",
        communityIncentives: "0",
        developmentFund: "40,000,000",
        liquidity: "0",
        status: "Pending",
    },
    {
        period: "TGE+40M",
        month: 40,
        gameplayRewards: "0",
        communityIncentives: "0",
        developmentFund: "40,000,000",
        liquidity: "0",
        status: "Pending",
    },
    {
        period: "TGE+41M",
        month: 41,
        gameplayRewards: "0",
        communityIncentives: "0",
        developmentFund: "40,000,000",
        liquidity: "0",
        status: "Pending",
    },
    {
        period: "TGE+42M",
        month: 42,
        gameplayRewards: "500,000,000",
        communityIncentives: "0",
        developmentFund: "40,000,000",
        liquidity: "0",
        status: "Pending",
    },
    {
        period: "TGE+43M",
        month: 43,
        gameplayRewards: "0",
        communityIncentives: "0",
        developmentFund: "40,000,000",
        liquidity: "0",
        status: "Pending",
    },
    {
        period: "TGE+44M",
        month: 44,
        gameplayRewards: "0",
        communityIncentives: "0",
        developmentFund: "40,000,000",
        liquidity: "0",
        status: "Pending",
    },
    {
        period: "TGE+45M",
        month: 45,
        gameplayRewards: "0",
        communityIncentives: "0",
        developmentFund: "40,000,000",
        liquidity: "0",
        status: "Pending",
    },
    {
        period: "TGE+46M",
        month: 46,
        gameplayRewards: "0",
        communityIncentives: "0",
        developmentFund: "40,000,000",
        liquidity: "0",
        status: "Pending",
    },
    {
        period: "TGE+47M",
        month: 47,
        gameplayRewards: "0",
        communityIncentives: "0",
        developmentFund: "40,000,000",
        liquidity: "0",
        status: "Pending",
    },
    {
        period: "TGE+48M",
        month: 48,
        gameplayRewards: "500,000,000",
        communityIncentives: "250,000,000",
        developmentFund: "40,000,000",
        liquidity: "0",
        status: "Pending",
    },
    {
        period: "TGE+49M",
        month: 49,
        gameplayRewards: "0",
        communityIncentives: "0",
        developmentFund: "40,000,000",
        liquidity: "0",
        status: "Pending",
    },
    {
        period: "TGE+50M",
        month: 50,
        gameplayRewards: "0",
        communityIncentives: "0",
        developmentFund: "40,000,000",
        liquidity: "0",
        status: "Pending",
    },
    {
        period: "TGE+51M",
        month: 51,
        gameplayRewards: "0",
        communityIncentives: "0",
        developmentFund: "40,000,000",
        liquidity: "0",
        status: "Pending",
    },
    {
        period: "TGE+52M",
        month: 52,
        gameplayRewards: "0",
        communityIncentives: "0",
        developmentFund: "40,000,000",
        liquidity: "0",
        status: "Pending",
    },
    {
        period: "TGE+53M",
        month: 53,
        gameplayRewards: "0",
        communityIncentives: "0",
        developmentFund: "5,000,000",
        liquidity: "0",
        status: "Pending",
    },
    {
        period: "TGE+54M",
        month: 54,
        gameplayRewards: "500,000,000",
        communityIncentives: "0",
        developmentFund: "5,000,000",
        liquidity: "0",
        status: "Pending",
    },
    {
        period: "TGE+55M",
        month: 55,
        gameplayRewards: "0",
        communityIncentives: "0",
        developmentFund: "5,000,000",
        liquidity: "0",
        status: "Pending",
    },
    {
        period: "TGE+56M",
        month: 56,
        gameplayRewards: "0",
        communityIncentives: "0",
        developmentFund: "5,000,000",
        liquidity: "0",
        status: "Pending",
    },
    {
        period: "TGE+59M",
        month: 59,
        gameplayRewards: "500,000,000",
        communityIncentives: "0",
        developmentFund: "0",
        liquidity: "0",
        status: "Pending",
    },
];

export const tokenCategories = {
    gameplayRewards: {
        label: "GAMEPLAY REWARDS",
        percentage: "60%",
        total: "6,000,000,000",
        color: "#10B981"
    },
    communityIncentives: {
        label: "COMMUNITY INCENTIVES",
        percentage: "15%",
        total: "1,500,000,000",
        color: "#34D399"
    },
    developmentFund: {
        label: "DEVELOPMENT FUND & INVESTOR",
        percentage: "15%",
        total: "1,500,000,000",
        color: "#6EE7B7"
    },
    liquidity: {
        label: "LIQUIDITY",
        percentage: "10%",
        total: "1,000,000,000",
        color: "#A7F3D0"
    }
};
